baseURL = 'https://monicatrinh.xyz/'
languageCode = 'en-us'
title = 'Monica Trinh'
paginate = 3
theme = 'maverick'

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/images/avatar.png'
  description = "Monica Personal Site"

  [params.comments]
    githubRepo = 'monmon0/mon-site'
    theme = 'github-light'


  [params.social.share]
    facebook = true
    linkedin = true
    twitter = true
    whatsapp = true
    email = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = "-300"

  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = -100


 [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = "-200"


[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"
  author = "author"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
